### PR TITLE
Feature/initial css html

### PR DESCRIPTION
**Pull request by Neil-B-Linton**
- [ ] fix 
- [x] feature?

## What does it change?
- Added HTML and CSS 

## What does it fix?
- N/A

## Where should reviewer start?
- from code line 1 on both HTML and CSS

## How can this be tested?
- open index.html

### CODE REVIEW

**Comment by Neil-B-Linton** [comment]
Please review the PR for our group project, and request changes if necessary

**Review by nhodnett — APPROVED** [review]
Looks great! Nice work team!!!

**Comment by orlov-n** [comment]
Incredible work!

**Review by orlov-n — APPROVED** [review]

**Comment by orlov-n** [comment]
Looks great!

**Comment by orlov-n** [comment]
Looks great!

**Pull request merged**
